export const LOADING = 'LOADING'
export const SUCCESS = 'SUCCESS'
export const FAIL = 'FAIL'
export const GET_ALL_SESSIONS = 'GET_ALL_SESSIONS'
export const GET_SOCKET = 'GET_SOCKET'
export const GET_AUDIO = 'GET_AUDIO'
export const SEND_DATA = 'SEND_DATA'